# Kactus2 Python automation script.
# This script automatically imports the 'ipxact_lib' library generated by py2hwsw.
#
# Kactus2 Python API functions: https://github.com/kactus2/kactus2dev/blob/main/PythonAPI/PythonAPI.cpp

import pythonAPI

api = pythonAPI.pythonAPI()

api.addLibraryPath("./ipxact_lib", True)

exit(0)
