# User API for interfacing with Py2HWSW
#
# Py2HWSW has 3 user interfaces in total:
# - Dictionary/JSON interface
# - Short notation interface
# - API interface
#
# The classes specify the API interface. User may instantiate/use any of the classes,
# their attributes, and methods.
#
# The 'dict2python' dictionary maps between the dictionary/JSON interface and the API
# interface.
# The 'short2python' dictionary maps between the short notation interface and the API
# interface.
#
# The mapping between the two interfaces does not have to be 1:1. Some mapping keys
# may call special conversion methods instead of setting the attribute directly.


# Note for developers:
# To achieve backwards compatibility, consider the following best practices:
#
# - Add new methods, don't change existing ones:
#       When adding new functionality, introduce new methods or interfaces instead of
#       modifying existing ones. This ensures that existing user code will not break.
# - Use default values or optional parameters:
#       When adding new parameters to existing methods, use default values or make
#       them optional to avoid breaking existing user code.
# - Avoid removing methods or interfaces:
#       Once a method or interface is published, avoid removing it in future versions.
#       Instead, consider deprecating it and providing a replacement or alternative
#       implementation.
# - Document changes and deprecations:
#       Clearly document any changes, deprecations, or removals in your API, including
#       the version number or identifier where the change occurred. This helps users
#       understand the impact of updates and plan accordingly.


from datetime import date
import os
import sys

sys.path.insert(
    0, os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), ".."))
)
from api_base import api_for, empty_list, empty_dict
import iob_conf as internal_conf
import iob_signal as internal_signal
import if_gen as internal_interface
import iob_wire as internal_wire
import iob_port as internal_port
import iob_snippet as internal_snippet
import iob_comb as internal_comb
import iob_fsm as internal_fsm
import iob_block as internal_block
import iob_license as internal_license
import iob_python_parameter as internal_python_parameter
import iob_core as internal_core


# NOTE: for developers:
# - Update py2hwsw version every time API changes!
#   Must change major version if new API is not backwards compatible.
#   Change minor version when adding new API methods or other non-breaking changes.

# NOTE: for users:
# - Every attribute must be accessed via setter/getter methods.
#   Users should use corresponding getters/setters [like `get_<attribute_name>()`/`set_<attribute_name>()`].
#   Some of these methods may be automatically generated by the decorator.
# - Classes have similar structure to python's '@dataclasses'
# - Methods are abstract. They do not contain implementation in the API.


#
# Confs
#
@api_for(internal_conf.iob_conf)
class iob_conf:
    """
    Class to represent a configuration option.

    Attributes:
        name (str): Configuration identifier name.
        kind (str): Configuration type, either M (Verilog macro), P (Verilog parameter), C (Constant) or D (Derived Parameter).
                    False-parameters are the same as verilog parameters except that the its value must not be overriden.
        value (str | int | bool): Configuration value.
        min_value (str | int): Minimum value supported by the configuration option (NA if not applicable).
        max_value (str | int): Maximum value supported by the configuration option (NA if not applicable).
        descr (str): Description of the configuration option.
        if_defined (str): Only applicable to Verilog macros: Conditionally enable this configuration if the specified Verilog macro is defined.
        if_not_defined (str): Only applicable to Verilog macros: Conditionally enable this configuration if the specified Verilog macro is undefined.
        doc_only (bool): If enabled, configuration option will only appear in documentation. Not in the verilog code.
    """

    name: str = ""
    kind: str = "P"
    value: str | int | bool = ""
    min_value: str | int = "NA"
    max_value: str | int = "NA"
    descr: str = "Default description"
    if_defined: str = ""
    if_not_defined: str = ""
    doc_only: bool = False

    def test_method(self, var1: str, var2: int) -> list:
        """Example docstring"""
        pass


@api_for(internal_conf.conf_from_dict)
def create_conf_from_dict(conf_dict):
    """
    Function to create iob_conf object from dictionary attributes.

    Attributes:
        conf_dict (dict): dictionary with values to initialize attributes of iob_conf object.
            This dictionary supports the following keys corresponding to the iob_conf attributes:
            - name           -> iob_conf.name
            - type           -> iob_conf.kind
            - val            -> iob_conf.value
            - min            -> iob_conf.min_value
            - max            -> iob_conf.max_value
            - descr          -> iob_conf.descr
            - if_defined     -> iob_conf.if_defined
            - if_not_defined -> iob_conf.if_not_defined
            - doc_only       -> iob_conf.doc_only

    Returns:
        iob_conf: iob_conf object
    """
    pass


@api_for(internal_conf.conf_from_text)
def create_conf_from_text(conf_text):
    """
    Function to create iob_conf object from short notation text.

    Attributes:
        conf_text (str): Short notation text. Object attributes are specified using the following format:
            name [-t kind] [-v value] [-m min_value] [-M max_value]

    Returns:
        iob_conf: iob_conf object
    """
    pass


@api_for(internal_conf.iob_conf_group)
class iob_conf_group:
    """
    Class to represent a group of configurations.

    Attributes:
        name (str): Configuration group identifier name.
        descr (str): Description of the configuration group.
        confs (list): List of configuration objects.
        doc_only (bool): If enabled, configuration group will only appear in documentation. Not in the verilog code.
        doc_clearpage (bool): If enabled, the documentation table for this group will be terminated by a TeX '\clearpage' command.
    """

    name: str = ""
    descr: str = "Default description"
    confs: list[iob_conf] = empty_list()
    doc_only: bool = False
    doc_clearpage: bool = False


@api_for(internal_conf.conf_group_from_dict)
def create_conf_group_from_dict(conf_group_dict):
    """
    Function to create iob_conf_group object from dictionary attributes.

    Attributes:
        conf_group_dict (dict): dictionary with values to initialize attributes of iob_conf_group object.
            This dictionary supports the following keys corresponding to the iob_conf_group attributes:
            - name          -> iob_conf_group.name
            - descr         -> iob_conf_group.descr
            - confs         -> iob_conf_group.confs
            - doc_only      -> iob_conf_group.doc_only
            - doc_clearpage -> iob_conf_group.doc_clearpage

    Returns:
        iob_conf_group: iob_conf_group object
    """
    pass


@api_for(internal_conf.conf_group_from_text)
def create_conf_group_from_text(conf_group_text):
    """
    Function to create iob_conf_group object from short notation text.

    Attributes:
        conf_group_text (str): Short notation text. Object attributes are specified using the following format:
            name [-c confs]

    Returns:
        iob_conf_group: iob_conf_group object
    """
    pass


#
# Signals
#


@api_for(internal_signal.iob_signal)
class iob_signal:
    """
    Class that represents a wire/port signal.

    Attributes:
        name (str): Identifier name for the signal.
        width (str or int): Number of bits in the signal.
        descr (str): Description of the signal.
        isvar (bool): If enabled, signal will be generated with type `reg` in Verilog.
        # isreg (bool): Used for `iob_comb`: If enabled, iob_comb will infer a register for this signal.
        # reg_signals (list): Used for `iob_comb`: List of signals associated to the infered register.
        # value (str or int): Logic value for future simulation effort using global signals list.
    """

    name: str = ""
    width: str or int = 1
    descr: str = "Default description"
    isvar: bool = False


@api_for(internal_signal.signal_from_dict)
def create_signal_from_dict(signal_dict):
    """
    Function to create iob_signal object from dictionary attributes.

    Attributes:
        signal_dict (dict): dictionary with values to initialize attributes of iob_signal object.
            This dictionary supports the following keys corresponding to the iob_signal attributes:
            - name          -> iob_signal.name
            - width         -> iob_signal.width
            - descr         -> iob_signal.descr
            - isvar         -> iob_signal.isvar
            - isreg         -> iob_signal.isreg
            - reg_signals   -> iob_signal.reg_signals
            - val           -> iob_signal.value

    Returns:
        iob_signal: iob_signal object
    """
    pass


@api_for(internal_signal.signal_from_text)
def create_signal_from_text(signal_text):
    """
    Function to create iob_signal object from short notation text.

    Attributes:
        signal_text (str): Short notation text. Object attributes are specified using the following format:
            name [-w width] [-d descr] [-r (enables isreg)] [-v value]

    Returns:
        iob_signal: iob_signal object
    """
    pass


#
# if_gen
#


# NOTE: artur: I believe the 'params' attribute could be merged with 'widths' attibute.
@api_for(internal_interface.interface)
class interface:
    """
    Class to represent an interface for generation.

    Attributes:
        kind (str): Type/Name of interface to generate.
        prefix (str): Prefix for signals of the interface.
        mult (str or int): Width multiplier. Used when concatenating multiple instances of the interface.
        params (str): Generic string parameter that is passed to "get_<interface>_ports" function
        widths (dict[str, str]): Dictionary of width properties of interface.
        file_prefix (str): Prefix for generated "Verilog Snippets" of this interface.
        portmap_port_prefix (str): Prefix for "Verilog snippets" of portmaps of this interface:
    """

    kind: str = ""
    prefix: str = ""
    mult: str | int = 1
    params: str = None
    widths: dict[str, str] = empty_dict()
    file_prefix: str = ""
    portmap_port_prefix: str = ""


@api_for(internal_interface.interface_from_dict)
def create_interface_from_dict(interface_dict):
    """
    Function to create interface object from dictionary attributes.

    Attributes:
        interface_dict (dict): dictionary with values to initialize attributes of interface object.
            This dictionary supports the following keys corresponding to the interface attributes:
            - kind          -> interface.kind
            - prefix        -> interface.prefix
            - mult          -> interface.mult
            - params        -> interface.params
            - widths        -> interface.widths
            - file_prefix   -> interface.file_prefix
            - portmap_port_prefix -> interface.portmap_port_prefix

    Returns:
        interface: interface object
    """
    pass


@api_for(internal_interface.interface_from_text)
def create_interface_from_text(interface_text):
    """
    Function to create interface object from short notation text.

    Attributes:
        interface_text (str): Short notation text. Object attributes are specified using the following format:
            type [-p prefix] [-m mult] [-w width] [-p params]

    Returns:
        interface: interface object
    """
    pass


#
# Wires
#
@api_for(internal_wire.iob_wire)
class iob_wire:
    """
    Class to represent a wire in an iob module.

    Attributes:
        name (str): Identifier name for the wire.
        interface (interface): Name of the standard interface to auto-generate with `if_gen.py` script.
        descr (str): Description of the wire.
        if_defined (str): Conditionally define this wire if the specified Verilog macro is defined/undefined.
        if_not_defined (str): Conditionally define this wire if the specified Verilog macro is defined/undefined.
        signals (list): List of signals belonging to this wire
                        (each signal represents a hardware Verilog wire).
    """

    name: str = ""
    interface: interface = None
    descr: str = "Default description"
    if_defined: str = ""
    if_not_defined: str = ""
    signals: list[iob_signal] = empty_list()

    def get_signal(self, signal_name: str) -> iob_signal:
        """
        Find a signal by name and return it.

        Args:
            signal_name (str): Name of the signal to find

        Returns:
            iob_signal: The found signal.
        """
        pass


@api_for(internal_wire.wire_from_dict)
def create_wire_from_dict(wire_dict):
    """
    Function to create iob_wire object from dictionary attributes.

    Attributes:
        wire_dict (dict): dictionary with values to initialize attributes of iob_wire object.
            This dictionary supports the following keys corresponding to the iob_wire attributes:
            - name           -> iob_wire.name
            - interface      -> iob_wire.interface
            - descr          -> iob_wire.descr
            - if_defined     -> iob_wire.if_defined
            - if_not_defined -> iob_wire.if_not_defined
            - signals        -> iob_wire.signals

    Returns:
        iob_wire: iob_wire object
    """
    pass


@api_for(internal_wire.wire_from_text)
def create_wire_from_text(wire_text):
    """
    Function to create iob_wire object from short notation text.

    Attributes:
        wire_text (str): Short notation text. Object attributes are specified using the following format:
            name [-i interface] [-d descr] [-s signal_name:width]+

    Returns:
        iob_wire: iob_wire object
    """
    pass


#
# Ports
#


@api_for(internal_port.iob_port)
class iob_port(iob_wire):
    """
    Describes an IO port.

    Attributes:
        e_connect (iob_wire): External wire to connect to.
        e_connect_bit_slices (list): List of bit slices of signals in e_connect
        doc_only (bool): Only add to documentation
        doc_clearpage (bool): If enabled, the documentation table for this port will be terminated by a TeX '\clearpage' command.
    """

    e_connect: iob_wire = None
    # FIXME: Constrain values received by bit slices
    e_connect_bit_slices: list[object] = empty_list()
    doc_only: bool = False
    doc_clearpage: bool = False


@api_for(internal_port.port_from_dict)
def create_port_from_dict(port_dict):
    """
    Function to create iob_port object from dictionary attributes.

    Attributes:
        port_dict (dict): dictionary with values to initialize attributes of iob_port object.
            This dictionary supports the following keys corresponding to the iob_port attributes:
            - e_connect      -> iob_port.e_connect
            - e_connect_bit_slices -> iob_port.e_connect_bit_slices
            - doc_only -> iob_port.doc_only
            - doc_clearpage -> iob_port.doc_clearpage
            (Also supports the keys inherited from iob_wire)

    Returns:
        iob_port: iob_port object
    """
    pass


@api_for(internal_port.port_from_text)
def create_port_from_text(port_text):
    """
    Function to create iob_port object from short notation text.

    Attributes:
        port_text (str): Short notation text. Object attributes are specified using the following format:
            name [-i interface] [-d descr] [-s signal_name:width]+

    Returns:
        iob_port: iob_port object
    """
    pass


#
# Snippets
#


@api_for(internal_snippet.iob_snippet)
class iob_snippet:
    """
    Class to represent a Verilog snippet in an iob module.

    Attributes:
        verilog_code (str): Verilog code string
    """

    verilog_code: str = ""


@api_for(internal_snippet.snippet_from_dict)
def create_snippet_from_dict(snippet_dict):
    """
    Function to create iob_snippet object from dictionary attributes.

    Attributes:
        snippet_dict (dict): dictionary with values to initialize attributes of iob_snippet object.
            This dictionary supports the following keys corresponding to the iob_snippet attributes:
            - verilog_code -> iob_snippet.verilog_code

    Returns:
        iob_snippet: iob_snippet object
    """
    pass


@api_for(internal_snippet.snippet_from_text)
def create_snippet_from_text(snippet_text):
    """
    Function to create iob_snippet object from short notation text.

    Attributes:
        snippet_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_snippet: iob_snippet object
    """
    pass


#
# Comb
#


@api_for(internal_comb.iob_comb)
class iob_comb(iob_snippet):
    """
    Class to represent a Verilog combinatory circuit in an iob module.

    Attributes:
        code (str): Verilog code string
        clk_if (str): Clock interface
    """

    code: str = ""
    clk_if: str = "c_a"


@api_for(internal_comb.comb_from_dict)
def create_comb_from_dict(comb_dict):
    """
    Function to create iob_comb object from dictionary attributes.

    Attributes:
        comb_dict (dict): dictionary with values to initialize attributes of iob_comb object.
            This dictionary supports the following keys corresponding to the iob_comb attributes:
            - code -> iob_comb.code
            - clk_if -> iob_comb.clk_if

    Returns:
        iob_comb: iob_comb object
    """
    pass


@api_for(internal_comb.comb_from_text)
def create_comb_from_text(comb_text):
    """
    Function to create iob_comb object from short notation text.

    Attributes:
        comb_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_comb: iob_comb object
    """
    pass


#
# FSM
#


@api_for(internal_fsm.iob_fsm)
class iob_fsm(iob_comb):
    """
    Class to represent a Verilog finite state machine in an iob module.

    Attributes:
        kind (str): Type of the finite state machine.
        default_assignments (str): Verilog code string to be assigned to the state register on reset.
        state_descriptions (str): Verilog code string to be used for state description
    """

    kind: str = "prog"
    default_assignments: str = ""
    state_descriptions: str = ""


@api_for(internal_fsm.fsm_from_dict)
def create_fsm_from_dict(fsm_dict):
    """
    Function to create iob_fsm object from dictionary attributes.

    Attributes:
        fsm_dict (dict): dictionary with values to initialize attributes of iob_fsm object.
            This dictionary supports the following keys corresponding to the iob_fsm attributes:
            - type -> iob_fsm.kind
            - default_assignments -> iob_fsm.default_assignments
            - state_descriptions -> iob_fsm.state_descriptions

    Returns:
        iob_fsm: iob_fsm object
    """
    pass


@api_for(internal_fsm.fsm_from_text)
def create_fsm_from_text(fsm_text):
    """
    Function to create iob_fsm object from short notation text.

    Attributes:
        fsm_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_fsm: iob_fsm object
    """
    pass


#
# Blocks
#


class iob_core:
    """Forward reference of iob_core class. Full declaration of iob_core class is available in below."""

    pass


@api_for(internal_block.iob_block_group)
class iob_block_group:
    """
    Class to represent a group of blocks.

    Attributes:
        name (str): Name of the block group.
        descr (str): Description of the block group.
        blocks (list): List of blocks in the block group.
        doc_clearpage (bool): If enabled, the documentation table for this group will be terminated by a TeX '\clearpage' command.
    """

    name: str = ""
    descr: str = "Default description"
    blocks: list[iob_core] = empty_list()
    doc_clearpage: bool = False


@api_for(internal_block.block_group_from_dict)
def create_block_group_from_dict(block_group_dict):
    """
    Function to create iob_block_group object from dictionary attributes.

    Attributes:
        block_group_dict (dict): dictionary with values to initialize attributes of iob_block_group object.
            This dictionary supports the following keys corresponding to the iob_block_group attributes:
            - name -> iob_block_group.name
            - descr -> iob_block_group.descr
            - blocks -> iob_block_group.blocks
            - doc_clearpage -> iob_block_group.doc_clearpage

    Returns:
        iob_block_group: iob_block_group object
    """
    pass


@api_for(internal_block.block_group_from_text)
def create_block_group_from_text(block_group_text):
    """
    Function to create iob_block_group object from short notation text.

    Attributes:
        block_group_text (str): Short notation text. Object attributes are specified using the following format:
            name [-b block]+

    Returns:
        iob_block_group: iob_block_group object
    """
    pass


#
# License
#


@api_for(internal_license.iob_license)
class iob_license:
    """
    Class that represents a license attribute.

    Attributes:
        name (str): Name of the license.
        year (int): Year of the license.
        author (str): Author of the license.
    """

    name: str = "MIT"
    year: int = date.today().year
    author: str = "IObundle, Lda"


@api_for(internal_license.license_from_dict)
def create_license_from_dict(license_dict):
    """
    Function to create iob_license object from dictionary attributes.

    Attributes:
        license_dict (dict): dictionary with values to initialize attributes of iob_license object.
            This dictionary supports the following keys corresponding to the iob_license attributes:
            - name -> iob_license.name
            - year -> iob_license.year
            - author -> iob_license.author

    Returns:
        iob_license: iob_license object
    """
    pass


@api_for(internal_license.license_from_text)
def create_license_from_text(license_text):
    """
    Function to create iob_license object from short notation text.

    Attributes:
        license_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_license: iob_license object
    """
    pass


#
# Python Parameter
#


@api_for(internal_python_parameter.iob_python_parameter)
class iob_python_parameter:
    """
    Class that represents a python parameter attribute.

    Attributes:
        name (str): Identifier name for the Python Parameter option.
        val (Any): Value of the Python Parameter option.
        descr (str): Description of the Python Parameter option.
    """

    name: str = ""
    val: object = ""
    descr: str = "Default description"


@api_for(internal_python_parameter.python_parameter_from_dict)
def create_python_parameter_from_dict(python_parameter_dict):
    """
    Function to create iob_python_parameter object from dictionary attributes.

    Attributes:
        python_parameter_dict (dict): dictionary with values to initialize attributes of iob_python_parameter object.
            This dictionary supports the following keys corresponding to the iob_python_parameter attributes:
            - name -> iob_python_parameter.name
            - val -> iob_python_parameter.val
            - descr -> iob_python_parameter.descr

    Returns:
        iob_python_parameter: iob_python_parameter object
    """
    pass


@api_for(internal_python_parameter.python_parameter_from_text)
def create_python_parameter_from_text(python_parameter_text):
    """
    Function to create iob_python_parameter object from short notation text.

    Attributes:
        python_parameter_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_python_parameter: iob_python_parameter object
    """
    pass


@api_for(internal_python_parameter.iob_python_parameter_group)
class iob_python_parameter_group:
    """
    Class that represents a group of Python Parameters.

    Attributes:
        name (str): Identifier name for the group of Python Parameters.
        descr (str): Description of the Python Parameter group.
        python_parameters (list): List of Python Parameter objects.
        doc_clearpage (bool): If enabled, the documentation table for this group will be terminated by a TeX '\clearpage' command.
    """

    name: str = ""
    descr: str = "Default description"
    python_parameters: list = empty_list()
    doc_clearpage: bool = False


@api_for(internal_python_parameter.python_parameter_group_from_dict)
def create_python_parameter_group_from_dict(python_parameter_group_dict):
    """
    Function to create iob_python_parameter_group object from dictionary attributes.

    Attributes:
        python_parameter_group_dict (dict): dictionary with values to initialize attributes of iob_python_parameter_group object.
            This dictionary supports the following keys corresponding to the iob_python_parameter_group attributes:
            - name -> iob_python_parameter_group.name
            - descr -> iob_python_parameter_group.descr
            - python_parameters -> iob_python_parameter_group.python_parameters
            - doc_clearpage -> iob_python_parameter_group.doc_clearpage

    Returns:
        iob_python_parameter_group: iob_python_parameter_group object
    """
    pass


@api_for(internal_python_parameter.python_parameter_group_from_text)
def create_python_parameter_group_from_text(python_parameter_group_text):
    """
    Function to create iob_python_parameter_group object from short notation text.

    Attributes:
        python_parameter_group_text (str): Short notation text. Object attributes are specified using the following format:
            TODO

    Returns:
        iob_python_parameter_group: iob_python_parameter_group object
    """
    pass


#
# Core
#


@api_for(internal_core.iob_core)
class iob_core:
    """
    Generic class to describe how to generate a base IOb IP core.

    Attributes:
        # Module attributes
        original_name (str): Original name of the module. (The module name commonly used in the files of the setup dir.)
        name (str): Name of the generated module.
        description (str): Description of the module.
        reset_polarity (str): Global reset polarity of the module. Can be 'positive' or 'negative'. (Will override all subblocks' reset polarities).
        confs (list): List of module macros and Verilog (false-)parameters
        ports (list): List of module ports
        wires (list): List of wires
        snippets (list): List of Verilog code snippets
        comb (iob_comb): Combinational circuit
        fsm (iob_fsm): Finite state machine
        subblocks (list): List of instances of other cores inside this core.
        superblocks (list): List of wrappers for this core. Will only be setup if this core is a top module, or a wrapper of the top module.
        sw_modules (list): List of software modules required by this core.

        # Instance attributes
        instance_name (str): Name of the instance. (Will be used as the instance's name in the Verilog module).
        instance_description (str): Description of the instance.
        parameters (dict): Verilog parameter values for this instance.
        if_defined (str): Only use this instance in Verilog if given Verilog macro is defined.
        if_not_defined (str): Only use this instance in Verilog if given Verilog macro is not defined.
        instantiate (bool): Select if should intantiate the module inside another Verilog module.
        connect (dict): Connections for ports of the instance.

        # Core attributes
        version (str): Core version. By default is the same as Py2HWSW version.",
        previous_version (str): Core previous version.",
        setup_dir (str): Path to root setup folder of the core.",
        build_dir (str): Path to folder of build directory to be generated for this project.",
        # instance_name (str): Name of an instance of this class.",
        use_netlist (bool): Copy `<SETUP_DIR>/CORE.v` netlist instead of `<SETUP_DIR>/hardware/src/*`",
        is_system (bool): Sets `IS_FPGA=1` in config_build.mk",
        board_list (list): List of FPGAs supported by this core. A standard folder will be created for each board in this list.",
        dest_dir (str): Relative path inside build directory to copy sources of this core. Will only sources from `hardware/src/*`",
        ignore_snippets (list): List of `.vs` file includes in verilog to ignore.",
        generate_hw (bool): Select if should try to generate `<corename>.v` from py2hwsw dictionary. Otherwise, only generate `.vs` files.",
        parent (dict): Select parent of this core (if any). If parent is set, that core will be used as a base for the current one. Any attributes of the current core will override/add to those of the parent.",
        is_top_module (bool): Selects if core is top module. Auto-filled. DO NOT CHANGE.",
        is_superblock (bool): Selects if core is superblock of another. Auto-filled. DO NOT CHANGE.",
        is_tester (bool): Generates makefiles and depedencies to run this core as if it was the top module. Used for testers (superblocks of top moudle).",
        python_parameters (list): List of core Python Parameters. Used for documentation.",
        license (iob_license): License for the core.",
        doc_conf (str): CSR Configuration to use.",
        title (str): Title of this core. Used for documentation.",
    """

    # Module attributes
    original_name: str = None
    name: str = ""
    description: str = "Default description"
    reset_polarity: str = None
    confs: list[iob_conf_group] = empty_list()
    ports: list[iob_port] = empty_list()
    wires: list[iob_wire] = empty_list()
    snippets: list[iob_snippet] = empty_list()
    comb: iob_comb = None
    fsm: iob_fsm = None
    subblocks: list[iob_block_group] = empty_list()
    superblocks: list[iob_block_group] = empty_list()
    sw_modules: list[iob_block_group] = empty_list()

    # Instance attributes
    instance_name: str = None
    instance_description: str = ""
    parameters: dict[str, int | str] = empty_dict()
    if_defined: str = ""
    if_not_defined: str = ""
    instantiate: bool = ""
    connect: dict[str, str] = empty_dict()

    # Core attributes
    version: str = None
    previous_version: str = None
    setup_dir: str = None
    build_dir: str = "build"
    # instance_name: str = None
    use_netlist: bool = False
    is_system: bool = False
    board_list: list[str] = empty_list()
    # dest_dir: str = "" # Should not be visible to the user
    ignore_snippets: list[str] = empty_list()
    generate_hw: bool = False
    parent: dict = empty_dict()  # FIXME: not sure if this will be needed in pythase?
    is_top_module: bool = False
    is_superblock: bool = False
    is_tester: bool = False
    python_parameters: list[object] = empty_list()
    license: iob_license = None
    doc_conf: str = ""
    title: str = ""

    def __init__(self, core_dictionary: dict = {}):
        """
        Constructor for cores.

        Attributes:
            core_dictionary (dict): Optional dictionary to initialize core attributes.
        """
        pass

    def generate_build_dir(self):
        """
        Standard method to generate build directory.
        May be overridden by user subclasses to generate custom files or run scripts during the build directory generation process.
        """
        pass


@api_for(internal_core.core_from_dict)
def create_core_from_dict(core_dict):
    """
    Function to create iob_core object from dictionary attributes.

    Attributes:
        core_dict (dict): dictionary with values to initialize attributes of iob_core object.
            This dictionary supports the following keys corresponding to the iob_core attributes:

            # Keys inherited from iob_module
            - original_name -> iob_module.original_name
            - name -> iob_module.name
            - description -> iob_module.description
            - reset_polarity -> iob_module.reset_polarity
            - confs -> iob_module.confs
            - ports -> iob_module.ports
            - wires -> iob_module.wires
            - snippets -> iob_module.snippets
            - comb -> iob_module.comb
            - fsm -> iob_module.fsm
            - subblocks -> iob_module.subblocks
            - superblocks -> iob_module.superblocks
            - sw_modules -> iob_module.sw_modules

            # Keys inherited from iob_instance
            - instance_name -> iob_instance.instance_name
            - instance_description -> iob_instance.instance_description
            - parameters -> iob_instance.parameters
            - if_defined -> iob_instance.if_defined
            - if_not_defined -> iob_instance.if_not_defined
            - instantiate -> iob_instance.instantiate
            - connect -> iob_instance.connect

            # Iob_core specific keys
            - version -> iob_core.version
            - previous_version -> iob_core.previous_version
            - setup_dir -> iob_core.setup_dir
            - build_dir -> iob_core.build_dir
            - use_netlist -> iob_core.use_netlist
            - is_system -> iob_core.is_system
            - board_list -> iob_core.board_list
            - ignore_snippets -> iob_core.ignore_snippets
            - generate_hw -> iob_core.generate_hw
            - parent -> iob_core.parent
            - is_top_module -> iob_core.is_top_module
            - is_superblock -> iob_core.is_superblock
            - is_tester -> iob_core.is_tester
            - python_parameters -> iob_core.python_parameters
            - license -> iob_core.license
            - doc_conf -> iob_core.doc_conf
            - title -> iob_core.title

    Returns:
        iob_core: iob_core object
    """
    pass


@api_for(internal_core.core_from_text)
def create_core_from_text(core_text):
    """
    Function to create iob_core object from short notation text.

    Attributes:
        core_text (str): Short notation text. Object attributes are specified using the following format:
            # Notation inherited from iob_module
            original_name

            # Notation inherited from iob_instance
            instance_name [-p parameter_name:parameter_value]+ [-c port_name:signal_name]+ [--no_instance]

            # Notation specific to iob_core
            [--dest_dir dest_dir]
            # Below are parameters specific to the 'iob_csrs' module. They should probably not belong in the Py2HWSW API.
            [--no_autoaddr]
            [--rw_overlap]
            [--csr_if csr_if]
                [--csr-group csr_group_name]
                    [-r reg_name:n_bits]
                        [-t type] [-m mode] [--rst_val rst_val] [--addr addr] [--log2n_items log2n_items]

    Returns:
        iob_core: iob_core object
    """
    pass
