# SPDX-FileCopyrightText: 2026 IObundle
#
# SPDX-License-Identifier: GPL-3.0-only

BOARD_SERVER=$(SMART_ZYNQ_SL_SERVER)
BOARD_USER=$(SMART_ZYNQ_SL_USER)
BOARD_SERIAL_PORT=$(SMART_ZYNQ_SL_SERIAL_PORT)

FPGA_PROG = xsct vivado/zynq_prog.tcl $(FPGA_TOP) $(BOARD_DEVICE_ID) $(BOARD)

FPGA_EXTRA_DIRS = .gen
