#!/bin/sh

# SPDX-FileCopyrightText: 2026 IObundle
#
# SPDX-License-Identifier: GPL-3.0-only

case "$1" in
    start)
        ifconfig eth0 192.168.74.2 netmask 255.255.255.0 up
        ;;
    stop)
        ifconfig eth0 down
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
