/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_UNIVERSAL_CONVERTER_AXI_IOB_CONF_H
#define H_IOB_UNIVERSAL_CONVERTER_AXI_IOB_CONF_H

#define IOB_UNIVERSAL_CONVERTER_AXI_IOB_ADDR_W 1
#define IOB_UNIVERSAL_CONVERTER_AXI_IOB_DATA_W 32
#define IOB_UNIVERSAL_CONVERTER_AXI_IOB_AXI_ID_W 1
#define IOB_UNIVERSAL_CONVERTER_AXI_IOB_AXI_LEN_W 8
#define IOB_UNIVERSAL_CONVERTER_AXI_IOB_VERSION 0x0081

#endif // H_IOB_UNIVERSAL_CONVERTER_AXI_IOB_CONF_H
