/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_UART_TESTER_IOB_AES_KU040_DB_G_CONF_H
#define H_IOB_UART_TESTER_IOB_AES_KU040_DB_G_CONF_H

#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_AXI_ID_W 4
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_AXI_LEN_W 8
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_AXI_ADDR_W 30
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_AXI_DATA_W 32
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_BAUD 115200
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_FREQ 100000000
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_XILINX 1
#define IOB_UART_TESTER_IOB_AES_KU040_DB_G_VERSION 0x0081

#endif // H_IOB_UART_TESTER_IOB_AES_KU040_DB_G_CONF_H
