/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_BOOTROM_CSRS_CSRS_H
#define H_IOB_BOOTROM_CSRS_CSRS_H

/** @file iob_bootrom_csrs.h
 *  @brief Function prototypes for the iob_bootrom core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_bootrom core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

// used address space width
/**
 * @def IOB_BOOTROM_CSRS_CSRS_ADDR_W
 * @brief Used core address space width.
 *
 * This macro defines the required address width in bits to access all core
 * CSRs.
 */
#define IOB_BOOTROM_CSRS_CSRS_ADDR_W 13

// Addresses
/**
 * @def IOB_BOOTROM_CSRS_ROM_ADDR
 * @brief rom CSR address.
 */
#define IOB_BOOTROM_CSRS_ROM_ADDR 0
/**
 * @def IOB_BOOTROM_CSRS_VERSION_ADDR
 * @brief version CSR address.
 */
#define IOB_BOOTROM_CSRS_VERSION_ADDR 4096

// Data widths (bit)
/**
 * @def IOB_BOOTROM_CSRS_ROM_W
 * @brief rom CSR Width.
 */
#define IOB_BOOTROM_CSRS_ROM_W 32
/**
 * @def IOB_BOOTROM_CSRS_VERSION_W
 * @brief version CSR Width.
 */
#define IOB_BOOTROM_CSRS_VERSION_W 16

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_bootrom_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Get rom value.
 * Bootloader ROM (read).
 * @param addr rom array address.
 * @return uint32_t rom value.
 */
uint32_t iob_bootrom_csrs_get_rom(int addr);
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_bootrom_csrs_get_version();

#endif // H_IOB_BOOTROM_CSRS__CSRS_H
