/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_TIMER_CSRS_CSRS_H
#define H_IOB_TIMER_CSRS_CSRS_H

/** @file iob_timer_csrs.h
 *  @brief Function prototypes for the iob_time core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_time core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

// used address space width
/**
 * @def IOB_TIMER_CSRS_CSRS_ADDR_W
 * @brief Used core address space width.
 *
 * This macro defines the required address width in bits to access all core
 * CSRs.
 */
#define IOB_TIMER_CSRS_CSRS_ADDR_W 4

// Addresses
/**
 * @def IOB_TIMER_CSRS_RESET_ADDR
 * @brief reset CSR address.
 */
#define IOB_TIMER_CSRS_RESET_ADDR 0
/**
 * @def IOB_TIMER_CSRS_ENABLE_ADDR
 * @brief enable CSR address.
 */
#define IOB_TIMER_CSRS_ENABLE_ADDR 1
/**
 * @def IOB_TIMER_CSRS_SAMPLE_ADDR
 * @brief sample CSR address.
 */
#define IOB_TIMER_CSRS_SAMPLE_ADDR 2
/**
 * @def IOB_TIMER_CSRS_DATA_LOW_ADDR
 * @brief data_low CSR address.
 */
#define IOB_TIMER_CSRS_DATA_LOW_ADDR 4
/**
 * @def IOB_TIMER_CSRS_DATA_HIGH_ADDR
 * @brief data_high CSR address.
 */
#define IOB_TIMER_CSRS_DATA_HIGH_ADDR 8
/**
 * @def IOB_TIMER_CSRS_VERSION_ADDR
 * @brief version CSR address.
 */
#define IOB_TIMER_CSRS_VERSION_ADDR 12

// Data widths (bit)
/**
 * @def IOB_TIMER_CSRS_RESET_W
 * @brief reset CSR Width.
 */
#define IOB_TIMER_CSRS_RESET_W 8
/**
 * @def IOB_TIMER_CSRS_ENABLE_W
 * @brief enable CSR Width.
 */
#define IOB_TIMER_CSRS_ENABLE_W 8
/**
 * @def IOB_TIMER_CSRS_SAMPLE_W
 * @brief sample CSR Width.
 */
#define IOB_TIMER_CSRS_SAMPLE_W 8
/**
 * @def IOB_TIMER_CSRS_DATA_LOW_W
 * @brief data_low CSR Width.
 */
#define IOB_TIMER_CSRS_DATA_LOW_W 32
/**
 * @def IOB_TIMER_CSRS_DATA_HIGH_W
 * @brief data_high CSR Width.
 */
#define IOB_TIMER_CSRS_DATA_HIGH_W 32
/**
 * @def IOB_TIMER_CSRS_VERSION_W
 * @brief version CSR Width.
 */
#define IOB_TIMER_CSRS_VERSION_W 16

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_timer_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set reset value.
 * Timer soft reset
 * @param value reset Value.
 */
void iob_timer_csrs_set_reset(uint8_t value);
/**
 * @brief Set enable value.
 * Timer enable
 * @param value enable Value.
 */
void iob_timer_csrs_set_enable(uint8_t value);
/**
 * @brief Set sample value.
 * Sample time counter value into a readable register
 * @param value sample Value.
 */
void iob_timer_csrs_set_sample(uint8_t value);
/**
 * @brief Get data_low value.
 * High part of the timer value, which has twice the width of the data word
 * width
 * @return uint32_t data_low value.
 */
uint32_t iob_timer_csrs_get_data_low();
/**
 * @brief Get data_high value.
 * Low part of the timer value, which has twice the width of the data word width
 * @return uint32_t data_high value.
 */
uint32_t iob_timer_csrs_get_data_high();
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_timer_csrs_get_version();

#endif // H_IOB_TIMER_CSRS__CSRS_H
