/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_UART_TESTER_IOB_VEXRISCV_CONF_H
#define H_IOB_UART_TESTER_IOB_VEXRISCV_CONF_H

#define IOB_UART_TESTER_IOB_VEXRISCV_AXI_ID_W 0
#define IOB_UART_TESTER_IOB_VEXRISCV_AXI_ADDR_W 0
#define IOB_UART_TESTER_IOB_VEXRISCV_AXI_DATA_W 0
#define IOB_UART_TESTER_IOB_VEXRISCV_AXI_LEN_W 0
#define IOB_UART_TESTER_IOB_VEXRISCV_VERSION 0x0001

#endif // H_IOB_UART_TESTER_IOB_VEXRISCV_CONF_H
