/*
 * SPDX-FileCopyrightText: 2025 IObundle, Lda
 *
 * SPDX-License-Identifier: MIT
 *
 * Py2HWSW Version 0.81 has generated this code
 * (https://github.com/IObundle/py2hwsw).
 */

#ifndef H_IOB_UART_CSRS_CSRS_H
#define H_IOB_UART_CSRS_CSRS_H

/** @file iob_uart_csrs.h
 *  @brief Function prototypes for the iob_uart core.
 *
 *  This file contains the function prototypes to access the Control and Status
 * Registers (CSRs) for the iob_uart core.
 *
 *  This file is automatically generated by Py2HWSW
 */

#include <stdint.h>

// used address space width
/**
 * @def IOB_UART_CSRS_CSRS_ADDR_W
 * @brief Used core address space width.
 *
 * This macro defines the required address width in bits to access all core
 * CSRs.
 */
#define IOB_UART_CSRS_CSRS_ADDR_W 3

// Addresses
/**
 * @def IOB_UART_CSRS_SOFTRESET_ADDR
 * @brief softreset CSR address.
 */
#define IOB_UART_CSRS_SOFTRESET_ADDR 0
/**
 * @def IOB_UART_CSRS_DIV_ADDR
 * @brief div CSR address.
 */
#define IOB_UART_CSRS_DIV_ADDR 2
/**
 * @def IOB_UART_CSRS_TXDATA_ADDR
 * @brief txdata CSR address.
 */
#define IOB_UART_CSRS_TXDATA_ADDR 4
/**
 * @def IOB_UART_CSRS_TXEN_ADDR
 * @brief txen CSR address.
 */
#define IOB_UART_CSRS_TXEN_ADDR 5
/**
 * @def IOB_UART_CSRS_RXEN_ADDR
 * @brief rxen CSR address.
 */
#define IOB_UART_CSRS_RXEN_ADDR 6
/**
 * @def IOB_UART_CSRS_TXREADY_ADDR
 * @brief txready CSR address.
 */
#define IOB_UART_CSRS_TXREADY_ADDR 0
/**
 * @def IOB_UART_CSRS_RXREADY_ADDR
 * @brief rxready CSR address.
 */
#define IOB_UART_CSRS_RXREADY_ADDR 1
/**
 * @def IOB_UART_CSRS_RXDATA_ADDR
 * @brief rxdata CSR address.
 */
#define IOB_UART_CSRS_RXDATA_ADDR 4
/**
 * @def IOB_UART_CSRS_VERSION_ADDR
 * @brief version CSR address.
 */
#define IOB_UART_CSRS_VERSION_ADDR 6

// Data widths (bit)
/**
 * @def IOB_UART_CSRS_SOFTRESET_W
 * @brief softreset CSR Width.
 */
#define IOB_UART_CSRS_SOFTRESET_W 8
/**
 * @def IOB_UART_CSRS_DIV_W
 * @brief div CSR Width.
 */
#define IOB_UART_CSRS_DIV_W 16
/**
 * @def IOB_UART_CSRS_TXDATA_W
 * @brief txdata CSR Width.
 */
#define IOB_UART_CSRS_TXDATA_W 8
/**
 * @def IOB_UART_CSRS_TXEN_W
 * @brief txen CSR Width.
 */
#define IOB_UART_CSRS_TXEN_W 8
/**
 * @def IOB_UART_CSRS_RXEN_W
 * @brief rxen CSR Width.
 */
#define IOB_UART_CSRS_RXEN_W 8
/**
 * @def IOB_UART_CSRS_TXREADY_W
 * @brief txready CSR Width.
 */
#define IOB_UART_CSRS_TXREADY_W 8
/**
 * @def IOB_UART_CSRS_RXREADY_W
 * @brief rxready CSR Width.
 */
#define IOB_UART_CSRS_RXREADY_W 8
/**
 * @def IOB_UART_CSRS_RXDATA_W
 * @brief rxdata CSR Width.
 */
#define IOB_UART_CSRS_RXDATA_W 8
/**
 * @def IOB_UART_CSRS_VERSION_W
 * @brief version CSR Width.
 */
#define IOB_UART_CSRS_VERSION_W 16

// Base Address
/**
 * @brief Set core base address.
 *
 * This function sets the base address for the core in the system. All other
 * accesses are offset from this base address.
 *
 * @param addr Base address for core.
 */
void iob_uart_csrs_init_baseaddr(uint32_t addr);

// IO read and write function prototypes
/**
 * @brief Write access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @param value Value to write.
 */
void iob_write(uint32_t addr, uint32_t data_w, uint32_t value);
/**
 * @brief Read access function prototype.
 *
 * @param addr Address to write to.
 * @param data_w Data width in bits.
 * @return uint32_t Read data value.
 */
uint32_t iob_read(uint32_t addr, uint32_t data_w);

// Core Setters and Getters
/**
 * @brief Set softreset value.
 * Soft reset
 * @param value softreset Value.
 */
void iob_uart_csrs_set_softreset(uint8_t value);
/**
 * @brief Set div value.
 * Bit duration in system clock cycles.
 * @param value div Value.
 */
void iob_uart_csrs_set_div(uint16_t value);
/**
 * @brief Set txdata value.
 * TX data.
 * @param value txdata Value.
 */
void iob_uart_csrs_set_txdata(uint8_t value);
/**
 * @brief Set txen value.
 * TX enable.
 * @param value txen Value.
 */
void iob_uart_csrs_set_txen(uint8_t value);
/**
 * @brief Set rxen value.
 * RX enable.
 * @param value rxen Value.
 */
void iob_uart_csrs_set_rxen(uint8_t value);
/**
 * @brief Get txready value.
 * TX ready to receive data.
 * @return uint8_t txready value.
 */
uint8_t iob_uart_csrs_get_txready();
/**
 * @brief Get rxready value.
 * RX ready to be read.
 * @return uint8_t rxready value.
 */
uint8_t iob_uart_csrs_get_rxready();
/**
 * @brief Get rxdata value.
 * RX data.
 * @return uint8_t rxdata value.
 */
uint8_t iob_uart_csrs_get_rxdata();
/**
 * @brief Get version value.
 * Product version. This 16-bit register uses nibbles to represent decimal
 * numbers using their binary values. The two most significant nibbles represent
 * the integral part of the version, and the two least significant nibbles
 * represent the decimal part. For example V12.34 is represented by 0x1234.
 * @return uint16_t version value.
 */
uint16_t iob_uart_csrs_get_version();

#endif // H_IOB_UART_CSRS__CSRS_H
