#This file was auto generated by iob_system_utils.py
USE_EXTMEM:=0
INIT_MEM:=1

# Tester targets to build and get UUT's hex files
RUN_DEPS+=get_uut_run_deps
BUILD_DEPS+=get_uut_build_deps

get_uut_build_deps:
	make -C $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/fpga build_deps
	-cp $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/fpga/*.hex .

get_uut_run_deps:
	make -C $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/fpga run_deps
	-cp $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/fpga/*.hex .

.PHONY: get_uut_build_deps get_uut_run_deps
