#This file was auto generated by iob_system_utils.py
PERIPHERALS ?=iob_uart iob_timer

# Tester target to build UUT's software
# Build UUT software with "TESTER" macro defined
UTARGETS+=build_uut_software
build_uut_software:
	make -C $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/software clean
	USER_CFLAGS=-DTESTER make -C $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/software build

.PHONY: build_uut_software
