#This file was auto generated by iob_system_utils.py

# Tester target to build and get UUT's hex files
BUILD_DEPS+=get_uut_hex

get_uut_hex:
	make -C $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/simulation build_hex
	-cp $(ROOT_DIR)/$(RELATIVE_PATH_TO_UUT)/hardware/simulation/*.hex .

.PHONY: get_uut_hex
